os: linux
language: python
dist: xenial
cache: pip
python:
  - '3.6'
  - '3.7'
env:
  matrix:
    - TORCH_VER="1.5.0"
    - TORCH_VER="1.6.0"
install:
  # Installing pip from master source due to https://github.com/pypa/pip/issues/9215
  - pip install git+https://github.com/pypa/pip.git
  #- pip install --upgrade pip
  - pip install --progress-bar off torch==$TORCH_VER
  - pip install --progress-bar off .[extras]
  - pip install pylint==2.6.0 flake8==3.8.2
  - pip install mypy==0.790
  - pip install pytest==5.1.3
  - pip install coverage codecov
script:
  - pylint petuum_med/ tests/
  - flake8 petuum_med/ tests/

after_success:
  - codecov

